// src/components/AboutPage.vue
<template>
  <p>Desktop Postflop v0.2.7</p>
  <p>Copyright (C) 2022 Wataru Inariba</p>
  <p>
    <a
      class="link"
      href="https://github.com/b-inary/desktop-postflop"
      target="_blank"
    >
      https://github.com/b-inary/desktop-postflop
    </a>
  </p>
</template>

<style scoped>
.link {
  @apply text-blue-500 hover:underline;
}
</style>

// src/features/about/AboutPage.tsx
export function AboutPage() {
  return (
    <div className="max-w-3xl text-sm text-gray-700">
      <p className="mb-3">
        Desktop Postflop is an open-source postflop solver interface for the
        local single-user solver server.
      </p>
      <a
        className="font-semibold text-blue-700 hover:text-blue-900"
        href="https://github.com/b-inary/desktop-postflop"
        rel="noreferrer"
        target="_blank"
      >
        GitHub
      </a>
    </div>
  );
}
