// src/features/bunching/BunchingEffect.tsx
import { InformationCircleIcon } from "@heroicons/react/20/solid";
import { useRef, useState } from "react";
import { useAppDispatch, useAppSelector } from "../../app/hooks";
import {
  setBunchingEnabled,
  setBunchingFlop,
  setBunchingRunning,
} from "../../app/slices/appSlice";
import { setRangeWeights } from "../../app/slices/rangesSlice";
import { RangeEditor } from "../ranges/RangeEditor";
import { RangeMiniViewer } from "../ranges/RangeMiniViewer";
import * as invokes from "../../invokes";
import { cardText, rangeRegex, trimRegex } from "../../utils";

const comboDenominator = (52 * 51) / 2;

export function BunchingEffect() {
  const dispatch = useAppDispatch();
  const config = useAppSelector((state) => state.config);
  const app = useAppSelector((state) => state.app);
  const isSolverRunning = app.isSolverRunning;
  const terminateFlag = useRef(false);
  const pauseFlag = useRef(false);
  const startTime = useRef(0);

  const [numThreads, setNumThreads] = useState(
    navigator.hardwareConcurrency || 1
  );
  const [editingPlayer, setEditingPlayer] = useState(-1);
  const [rangeTexts, setRangeTexts] = useState(["", "", "", ""]);
  const [isRangeTextError, setIsRangeTextError] = useState([
    false,
    false,
    false,
    false,
  ]);
  const [numCombos, setNumCombos] = useState([0, 0, 0, 0]);
  const [rangeTextCopy, setRangeTextCopy] = useState("");
  const [statusText, setStatusText] = useState("No bunching data");
  const [flopCopy, setFlopCopy] = useState<number[]>([]);
  const [hasBunchingRun, setHasBunchingRun] = useState(false);
  const [isBunchingPaused, setIsBunchingPaused] = useState(false);
  const [elapsedTimeMs, setElapsedTimeMs] = useState(-1);

  const patchRangeText = (player: number, value: string) => {
    setRangeTexts((items) =>
      items.map((item, index) => (index === player ? value : item))
    );
  };

  const patchRangeError = (player: number, value: boolean) => {
    setIsRangeTextError((items) =>
      items.map((item, index) => (index === player ? value : item))
    );
  };

  const patchNumCombos = (player: number, value: number) => {
    setNumCombos((items) =>
      items.map((item, index) => (index === player ? value : item))
    );
  };

  const updateRangeWeights = async (player: number) => {
    const weights = await invokes.rangeGetWeights(player + 2);
    dispatch(
      setRangeWeights({
        player: player + 2,
        weights: weights.map((value) => value * 100),
      })
    );
    patchRangeError(player, false);
  };

  const updateRangeLocal = async (player: number) => {
    patchRangeText(player, await invokes.rangeToString(player + 2));
    patchNumCombos(player, await invokes.rangeNumCombos(player + 2));
  };

  const editRange = async (player: number) => {
    setRangeTextCopy(await invokes.rangeToString(player + 2));
    setEditingPlayer(player);
  };

  const onRangeTextChange = async (player: number) => {
    const trimmed = rangeTexts[player].replace(trimRegex, "$1").trim();
    const ranges = trimmed.split(",");

    if (ranges[ranges.length - 1] === "") ranges.pop();

    for (const range of ranges) {
      if (!rangeRegex.test(range)) {
        patchRangeError(player, true);
        return;
      }
    }

    const errorString = await invokes.rangeFromString(player + 2, trimmed);
    if (errorString) {
      patchRangeError(player, true);
      return;
    }

    await updateRangeWeights(player);
    await updateRangeLocal(player);
  };

  const invertRange = async (player: number) => {
    await invokes.rangeInvert(player + 2);
    await updateRangeWeights(player);
    await updateRangeLocal(player);
  };

  const clearRange = async (player: number) => {
    await invokes.rangeClear(player + 2);
    await updateRangeWeights(player);
    await updateRangeLocal(player);
  };

  const resumePrecomputation = async () => {
    dispatch(setBunchingRunning(true));
    setIsBunchingPaused(false);
    startTime.current = performance.now();
    await invokes.setNumThreads(numThreads);

    while (true) {
      if (terminateFlag.current) {
        await invokes.bunchingClear();
        dispatch(setBunchingFlop([]));
        setStatusText("No bunching data");
        setHasBunchingRun(false);
        break;
      }

      if (pauseFlag.current) {
        setIsBunchingPaused(true);
        break;
      }

      const [phase, percent] = await invokes.bunchingProgress();

      if (phase === 3 && percent === 100) {
        dispatch(setBunchingFlop(flopCopy));
        setStatusText("Bunching data ready!");
        break;
      }

      setStatusText(`Phase ${phase}/3 - ${percent}% completed...`);
    }

    setElapsedTimeMs((value) => {
      const base = value < 0 ? 0 : value;
      return base + performance.now() - startTime.current;
    });

    if (!terminateFlag.current && !pauseFlag.current) {
      const nextElapsed =
        (elapsedTimeMs < 0 ? 0 : elapsedTimeMs) +
        performance.now() -
        startTime.current;
      setStatusText(
        (text) => `${text} (Time: ${(nextElapsed / 1000).toFixed(2)}s)`
      );
    }

    dispatch(setBunchingRunning(false));
    terminateFlag.current = false;
    pauseFlag.current = false;
  };

  const runPrecomputation = async () => {
    dispatch(setBunchingFlop([]));
    const errorString = await invokes.bunchingInit(config.board);
    if (errorString) {
      setStatusText(`Error: ${errorString}`);
      return;
    }

    setStatusText("Phase 1/3 - Preparing...");
    setFlopCopy(config.board.slice(0, 3));
    setHasBunchingRun(true);
    setElapsedTimeMs(0);
    await resumePrecomputation();
  };

  const clearPrecomputation = async () => {
    if (app.isBunchingRunning) {
      terminateFlag.current = true;
      return;
    }

    await invokes.bunchingClear();
    dispatch(setBunchingFlop([]));
    setStatusText("No bunching data");
    setHasBunchingRun(false);
    setIsBunchingPaused(false);
  };

  const saveEdit = async () => {
    patchRangeError(editingPlayer, false);
    await updateRangeLocal(editingPlayer);
    setEditingPlayer(-1);
  };

  const cancelEdit = async () => {
    patchRangeText(editingPlayer, rangeTextCopy);
    await invokes.rangeFromString(editingPlayer + 2, rangeTextCopy);
    await updateRangeWeights(editingPlayer);
    setEditingPlayer(-1);
  };

  if (editingPlayer !== -1) {
    return (
      <RangeEditor
        defaultText={rangeTextCopy}
        onCancel={cancelEdit}
        onSave={saveEdit}
        player={editingPlayer + 2}
      />
    );
  }

  return (
    <div>
      <div className="flex">
        <div className="flex rounded-md border-2 border-cyan-600 bg-cyan-50 py-1 pl-2.5 pr-3 font-semibold text-cyan-600">
          <InformationCircleIcon className="mr-1.5 mt-[0.1875rem] inline h-5 w-5" />
          <div>
            Enabling the bunching effect will significantly slow down the
            solver.
            <br />
            If you are not sure, we recommend leaving it disabled.
          </div>
        </div>
      </div>

      <div className="mt-4 flex items-center gap-8">
        <label className="cursor-pointer">
          <input
            checked={app.isBunchingEnabled}
            className="mr-1 rounded align-middle"
            onChange={(event) =>
              dispatch(setBunchingEnabled(event.target.checked))
            }
            type="checkbox"
          />
          Enable bunching effect
        </label>
      </div>

      {app.isBunchingEnabled && (
        <div className="mt-6">
          <div className="flex gap-8">
            {Array.from({ length: 4 }, (_, player) => (
              <div key={player}>
                <div className="text-[1.0625rem]">Fold Range {player + 1}</div>
                <RangeMiniViewer
                  className="mt-2 h-44 w-44 cursor-pointer"
                  onClick={() => editRange(player)}
                  player={player + 2}
                />
                <input
                  className={[
                    "mt-3 w-44 rounded-lg px-2 py-1 text-sm",
                    isRangeTextError[player] ? "input-error" : "",
                  ].join(" ")}
                  onBlur={() => onRangeTextChange(player)}
                  onChange={(event) =>
                    patchRangeText(player, event.target.value)
                  }
                  onFocus={(event) => event.currentTarget.select()}
                  type="text"
                  value={rangeTexts[player]}
                />
                <div className="mt-2 text-center">
                  {numCombos[player].toFixed(1)} combos (
                  {numCombos[player] >= 0.9995 * comboDenominator
                    ? "100"
                    : ((numCombos[player] * 100) / comboDenominator).toFixed(1)}
                  %)
                </div>
                <div className="mt-3 flex w-full justify-center gap-3">
                  <button
                    className="button-base button-blue"
                    onClick={() => invertRange(player)}
                    type="button"
                  >
                    Invert
                  </button>
                  <button
                    className="button-base button-blue"
                    onClick={() => clearRange(player)}
                    type="button"
                  >
                    Clear
                  </button>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-8 flex items-center gap-3">
            <button
              className="button-base button-blue"
              disabled={
                numCombos.every((x) => x === 0) ||
                app.isBunchingRunning ||
                isSolverRunning ||
                numThreads < 1 ||
                numThreads > 64 ||
                numThreads % 1 !== 0
              }
              onClick={runPrecomputation}
              type="button"
            >
              Run Precomputation
            </button>
            <button
              className="button-base button-red"
              disabled={!hasBunchingRun}
              onClick={clearPrecomputation}
              type="button"
            >
              Clear
            </button>
            {!isBunchingPaused ? (
              <button
                className="button-base button-green"
                disabled={!app.isBunchingRunning}
                onClick={() => {
                  pauseFlag.current = true;
                }}
                type="button"
              >
                Pause
              </button>
            ) : (
              <button
                className="button-base button-green"
                disabled={
                  isSolverRunning ||
                  numThreads < 1 ||
                  numThreads > 64 ||
                  numThreads % 1 !== 0
                }
                onClick={resumePrecomputation}
                type="button"
              >
                Resume
              </button>
            )}

            <span className="pl-3">
              Number of threads:
              <input
                className={[
                  "ml-1.5 w-20 rounded-lg px-2 py-1 text-center text-sm",
                  numThreads < 1 || numThreads > 64 || numThreads % 1 !== 0
                    ? "input-error"
                    : "",
                ].join(" ")}
                max="64"
                min="1"
                onChange={(event) => setNumThreads(Number(event.target.value))}
                type="number"
                value={numThreads}
              />
            </span>
            <span className="pl-3">
              RAM usage:{" "}
              {
                ["-", "60MB", "60MB", "190MB", "3.5GB"][
                  numCombos.filter((x) => x > 0).length
                ]
              }
            </span>
          </div>

          <div className="mt-3">
            <span className="flex items-center">
              Status:
              {app.isBunchingRunning && (
                <span className="spinner ml-2 mr-2.5 inline-block" />
              )}
              {statusText}
            </span>
            {app.bunchingFlop.length > 0 && (
              <span>
                [Flop:{" "}
                {app.bunchingFlop.map(cardText).map((item) => (
                  <span
                    className={`mx-px inline-block ${item.colorClass}`}
                    key={item.rank + item.suit}
                  >
                    {item.rank + item.suit}
                  </span>
                ))}
                ]
              </span>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// src/components/BunchingEffect.vue
<template>
  <div v-if="editingPlayer === -1">
    <div class="flex">
      <div
        class="flex pl-2.5 pr-3 py-1 text-cyan-600 bg-cyan-50 border-2 border-cyan-600 rounded-md font-semibold"
      >
        <InformationCircleIcon class="inline w-5 h-5 mt-[0.1875rem] mr-1.5" />
        <div>
          Enabling the bunching effect will significantly slow down the
          solver.<br />
          If you are not sure, we recommend leaving it disabled.
        </div>
      </div>
    </div>

    <div class="flex mt-4 gap-8 items-center">
      <label class="cursor-pointer">
        <input
          v-model="store.isBunchingEnabled"
          class="mr-1 align-middle rounded"
          type="checkbox"
        />
        Enable bunching effect
      </label>

      <div class="flex">
        <Tippy
          :delay="[200, 0]"
          :interactive="true"
          class="inline-block cursor-help text-gray-600"
          max-width="500px"
          placement="bottom"
          trigger="mouseenter click"
        >
          <QuestionMarkCircleIcon class="inline w-5 h-5" />
          <div class="inline-block ml-0.5 text-sm underline">
            What is the bunching effect?
          </div>
          <template #content>
            <div class="px-1 py-0.5 text-justify">
              <div>
                The bunching effect refers to the card removal effect caused by
                the ranges of folded players. Since most players fold with a
                weak hand, the remaining players will have a higher chance of
                holding a strong hand.
              </div>
              <div class="mt-3">
                This option supports up to 4 folded players (6-max game). By
                entering the ranges of the folded players and performing a
                precomputation, the solver can account for the bunching effect.
              </div>
              <div class="mt-3">
                The simulation is exact and precise. This means that the solver
                does not make any abstractions or approximations. However,
                please note that enabling the bunching effect will significantly
                slow down the solver due to the heavy additional computation
                required.
              </div>
            </div>
          </template>
        </Tippy>
      </div>
    </div>

    <div v-if="store.isBunchingEnabled" class="mt-6">
      <div class="flex gap-8">
        <div v-for="i in 4" :key="i">
          <div class="text-[1.0625rem]">Fold Range {{ i }}</div>
          <RangeMiniViewer
            :player="i + 1"
            class="w-44 h-44 mt-2 cursor-pointer"
            @click="editRange(i - 1)"
          />
          <input
            v-model="rangeTexts[i - 1]"
            :class="
              'w-44 mt-3 px-2 py-1 rounded-lg text-sm ' +
              (isRangeTextError[i - 1] ? ' input-error' : '')
            "
            type="text"
            @change="onRangeTextChange(i - 1)"
            @focus="($event.target as HTMLInputElement).select()"
          />
          <div class="mt-2 text-center">
            {{ numCombos[i - 1].toFixed(1) }} combos ({{
              numCombos[i - 1] >= 0.9995 * ((52 * 51) / 2)
                ? "100"
                : ((numCombos[i - 1] * 100) / ((52 * 51) / 2)).toFixed(1)
            }}%)
          </div>
          <div class="flex mt-3 w-full justify-center gap-3">
            <button class="button-base button-blue" @click="invertRange(i - 1)">
              Invert
            </button>
            <button class="button-base button-blue" @click="clearRange(i - 1)">
              Clear
            </button>
          </div>
        </div>
      </div>

      <div class="flex mt-8 gap-3 items-center">
        <button
          :disabled="
            numCombos.every((x) => x === 0) ||
            store.isBunchingRunning ||
            store.isSolverRunning ||
            numThreads < 1 ||
            numThreads > 64 ||
            numThreads % 1 !== 0
          "
          class="button-base button-blue"
          @click="runPrecomputation"
        >
          Run Precomputation
        </button>
        <button
          :disabled="!hasBunchingRun"
          class="button-base button-red"
          @click="clearPrecomputation"
        >
          Clear
        </button>
        <button
          v-if="!isBunchingPaused"
          :disabled="!store.isBunchingRunning"
          class="button-base button-green"
          @click="() => (pauseFlag = true)"
        >
          Pause
        </button>
        <button
          v-else
          :disabled="
            store.isSolverRunning ||
            numThreads < 1 ||
            numThreads > 64 ||
            numThreads % 1 !== 0
          "
          class="button-base button-green"
          @click="resumePrecomputation"
        >
          Resume
        </button>

        <span class="pl-3">
          Number of threads:
          <input
            v-model="numThreads"
            :class="
              'w-20 ml-1.5 px-2 py-1 rounded-lg text-sm text-center ' +
              (numThreads < 1 || numThreads > 64 || numThreads % 1 !== 0
                ? 'input-error'
                : '')
            "
            max="64"
            min="1"
            type="number"
          />
        </span>
        <span class="pl-3">
          RAM usage:
          {{
            ["-", "60MB", "60MB", "190MB", "3.5GB"][
              numCombos.filter((x) => x > 0).length
            ]
          }}
        </span>
      </div>

      <div class="mt-3">
        <span class="flex items-center">
          Status:
          <span
            v-if="store.isBunchingRunning"
            class="spinner inline-block ml-2 mr-2.5"
          ></span>
          {{ statusText }}
        </span>
        <span v-if="store.bunchingFlop.length > 0">
          [Flop:
          <span
            v-for="item in store.bunchingFlop.map(cardText)"
            :key="item.rank + item.suit"
            :class="'inline-block mx-px ' + item.colorClass"
            >{{ item.rank + item.suit }}</span
          >]
        </span>
      </div>
    </div>
  </div>

  <RangeEditor
    v-else
    :default-text="rangeTextCopy"
    :player="editingPlayer + 2"
    @cancel="cancelEdit"
    @save="saveEdit"
  />
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { useConfigStore, useStore } from "../store";
import { cardText, rangeRegex, trimRegex } from "../utils";
import * as invokes from "../invokes";

import RangeEditor from "./RangeEditor.vue";
import RangeMiniViewer from "./RangeMiniViewer.vue";
import { Tippy } from "vue-tippy";
import {
  InformationCircleIcon,
  QuestionMarkCircleIcon,
} from "@heroicons/vue/20/solid";

const store = useStore();
const configStore = useConfigStore();

const numThreads = ref(navigator.hardwareConcurrency || 1);

const editingPlayer = ref(-1);
const rangeTexts = ref(["", "", "", ""]);
const isRangeTextError = ref([false, false, false, false]);
const numCombos = ref([0, 0, 0, 0]);
const rangeTextCopy = ref("");

const statusText = ref("No bunching data");
const flopCopy = ref<number[]>([]);
const hasBunchingRun = ref(false);
const isBunchingPaused = ref(false);
const terminateFlag = ref(false);
const pauseFlag = ref(false);
const elapsedTimeMs = ref(-1);

let startTime = 0;

const onUpdate = async (player: number) => {
  const weights = await invokes.rangeGetWeights(player + 2);
  for (let i = 0; i < 13 * 13; ++i) {
    store.ranges[player + 2][i] = weights[i] * 100;
  }
  isRangeTextError.value[player] = false;
};

const onUpdateLocal = async (player: number) => {
  rangeTexts.value[player] = await invokes.rangeToString(player + 2);
  numCombos.value[player] = await invokes.rangeNumCombos(player + 2);
};

const editRange = async (player: number) => {
  rangeTextCopy.value = await invokes.rangeToString(player + 2);
  store.headers["bunching"].push(`Fold Range ${player + 1}`);
  editingPlayer.value = player;
};

const onRangeTextChange = async (player: number) => {
  const trimmed = rangeTexts.value[player].replace(trimRegex, "$1").trim();
  const ranges = trimmed.split(",");

  if (ranges[ranges.length - 1] === "") {
    ranges.pop();
  }

  for (const range of ranges) {
    if (!rangeRegex.test(range)) {
      isRangeTextError.value[player] = true;
      return;
    }
  }

  const errorString = await invokes.rangeFromString(player + 2, trimmed);

  if (errorString) {
    isRangeTextError.value[player] = true;
  } else {
    await onUpdate(player);
    await onUpdateLocal(player);
  }
};

const invertRange = async (player: number) => {
  await invokes.rangeInvert(player + 2);
  await onUpdate(player);
  await onUpdateLocal(player);
};

const clearRange = async (player: number) => {
  await invokes.rangeClear(player + 2);
  await onUpdate(player);
  await onUpdateLocal(player);
};

const runPrecomputation = async () => {
  store.bunchingFlop = [];

  const errorString = await invokes.bunchingInit(configStore.board);
  if (errorString) {
    statusText.value = `Error: ${errorString}`;
    return;
  }

  statusText.value = "Phase 1/3 - Preparing...";
  flopCopy.value = configStore.board.slice(0, 3);
  hasBunchingRun.value = true;
  elapsedTimeMs.value = 0;
  await resumePrecomputation();
};

const clearPrecomputation = async () => {
  if (store.isBunchingRunning) {
    terminateFlag.value = true;
  } else {
    await invokes.bunchingClear();
    store.bunchingFlop = [];
    statusText.value = "No bunching data";
    hasBunchingRun.value = false;
    isBunchingPaused.value = false;
  }
};

const resumePrecomputation = async () => {
  store.isBunchingRunning = true;
  isBunchingPaused.value = false;
  startTime = performance.now();
  await invokes.setNumThreads(numThreads.value);

  while (true) {
    if (terminateFlag.value) {
      await invokes.bunchingClear();
      store.bunchingFlop = [];
      statusText.value = "No bunching data";
      hasBunchingRun.value = false;
      break;
    }

    if (pauseFlag.value) {
      isBunchingPaused.value = true;
      break;
    }

    const [phase, percent] = await invokes.bunchingProgress();

    if (phase === 3 && percent === 100) {
      store.bunchingFlop = flopCopy.value;
      statusText.value = "Bunching data ready!";
      break;
    }

    statusText.value = `Phase ${phase}/3 - ${percent}% completed...`;
  }

  elapsedTimeMs.value += performance.now() - startTime;

  if (!terminateFlag.value && !pauseFlag.value) {
    statusText.value += ` (Time: ${(elapsedTimeMs.value / 1000).toFixed(2)}s)`;
  }

  store.isBunchingRunning = false;
  terminateFlag.value = false;
  pauseFlag.value = false;
};

const saveEdit = async () => {
  isRangeTextError.value[editingPlayer.value] = false;
  await onUpdateLocal(editingPlayer.value);
  store.headers["bunching"].pop();
  editingPlayer.value = -1;
};

const cancelEdit = async () => {
  rangeTexts.value[editingPlayer.value] = rangeTextCopy.value;
  await invokes.rangeFromString(editingPlayer.value + 2, rangeTextCopy.value);
  await onUpdate(editingPlayer.value);
  store.headers["bunching"].pop();
  editingPlayer.value = -1;
};
</script>
