// src/features/tree/TreeEditor.tsx
import { CheckIcon } from "@heroicons/react/20/solid";
import { TrashIcon } from "@heroicons/react/24/outline";
import { useEffect, useMemo, useRef, useState } from "react";
import { useAppSelector } from "../../app/hooks";
import type {
  Spot,
  SpotChance,
  SpotPlayer,
  SpotRoot,
} from "../../result-types";
import { convertBetString, readableLineString } from "../../utils";
import * as invokes from "../../invokes";

type TreeEditorProps = {
  onSave: (addedLines: string, removedLines: string) => void;
  onCancel: () => void;
};

function splitLines(lines: string) {
  return lines === "" ? [] : lines.split(",").map(readableLineString);
}

export function TreeEditor({ onCancel, onSave }: TreeEditorProps) {
  const config = useAppSelector((state) => state.config);
  const navRef = useRef<HTMLDivElement | null>(null);
  const spotsRef = useRef<Spot[]>([]);
  const selectedSpotIndexRef = useRef(-1);
  const totalBetAmountRef = useRef([0, 0]);
  const isLockedRef = useRef(false);

  const [isLoading, setIsLoading] = useState(true);
  const [isTreeError, setIsTreeError] = useState(false);
  const [spots, setSpots] = useState<Spot[]>([]);
  const [selectedSpotIndex, setSelectedSpotIndex] = useState(-1);
  const [betAmount, setBetAmount] = useState(0);
  const [totalBetAmount, setTotalBetAmount] = useState([0, 0]);
  const [prevBetAmount, setPrevBetAmount] = useState(0);
  const [addedLines, setAddedLines] = useState("");
  const [removedLines, setRemovedLines] = useState("");
  const [invalidLines, setInvalidLines] = useState("");

  const boardLength = config.expectedBoardLength;
  const rootSpot: SpotRoot = useMemo(
    () => ({
      type: "root",
      index: 0,
      player: boardLength === 3 ? "flop" : boardLength === 4 ? "turn" : "river",
      selectedIndex: -1,
      board: config.board,
      pot: config.startingPot,
      stack: config.effectiveStack,
    }),
    [boardLength, config.board, config.effectiveStack, config.startingPot]
  );

  const setSpotsValue = (nextSpots: Spot[]) => {
    spotsRef.current = nextSpots;
    setSpots([...nextSpots]);
  };

  const setSelectedValue = (index: number) => {
    selectedSpotIndexRef.current = index;
    setSelectedSpotIndex(index);
  };

  const setTotalValue = (value: number[]) => {
    totalBetAmountRef.current = value;
    setTotalBetAmount(value);
  };

  const refreshLines = async () => {
    setAddedLines(await invokes.treeAddedLines());
    setRemovedLines(await invokes.treeRemovedLines());
    setInvalidLines(await invokes.treeInvalidTerminals());
  };

  const isSelectedTerminal = useMemo(() => {
    if (isLockedRef.current || selectedSpotIndex === -1) return false;
    return spots[selectedSpotIndex]?.type === "terminal";
  }, [selectedSpotIndex, spots]);

  const isAfterAllin = useMemo(
    () => Math.max(...totalBetAmount) === config.effectiveStack,
    [config.effectiveStack, totalBetAmount]
  );

  const maxAmount = useMemo(() => {
    if (isSelectedTerminal) return 0;
    const maxTotalBetAmount = Math.max(...totalBetAmount);
    return config.effectiveStack - (maxTotalBetAmount - prevBetAmount);
  }, [
    config.effectiveStack,
    isSelectedTerminal,
    prevBetAmount,
    totalBetAmount,
  ]);

  const minAmount = useMemo(() => {
    const betMinus = config.effectiveStack - maxAmount;
    const min = Math.min(...totalBetAmount) - betMinus;
    const max = Math.max(...totalBetAmount) - betMinus;
    return Math.min(Math.max(2 * max - min, 1), maxAmount);
  }, [config.effectiveStack, maxAmount, totalBetAmount]);

  const amountRate = useMemo(() => {
    const pot = config.startingPot + 2 * Math.max(...totalBetAmount);
    const amount = betAmount - prevBetAmount;
    return amount / pot;
  }, [betAmount, config.startingPot, prevBetAmount, totalBetAmount]);

  const existingAmounts = useMemo(() => {
    if (isLockedRef.current || selectedSpotIndex === -1) return [];
    const spot = spots[selectedSpotIndex];
    if (!spot || spot.type !== "player") return [];
    return spot.actions
      .filter((action) => action.amount !== "0")
      .map((action) => Number(action.amount));
  }, [selectedSpotIndex, spots]);

  const addedLinesArray = useMemo(() => splitLines(addedLines), [addedLines]);
  const removedLinesArray = useMemo(
    () => splitLines(removedLines),
    [removedLines]
  );
  const invalidLinesArray = useMemo(
    () => splitLines(invalidLines),
    [invalidLines]
  );

  const encodeLine = (spotIndex: number) => {
    const ret: string[] = [];
    const currentSpots = spotsRef.current;
    for (let i = 1; i < spotIndex; ++i) {
      const spot = currentSpots[i];
      if (spot.type !== "player") continue;
      const action = spot.actions[spot.selectedIndex];
      if (!action) continue;
      if (action.name === "Fold") ret.push("F");
      else if (action.name === "Check") ret.push("X");
      else if (action.name === "Call") ret.push("C");
      else if (action.name === "Bet") ret.push("B" + action.amount);
      else if (action.name === "Raise") ret.push("R" + action.amount);
      else if (action.name === "Allin") ret.push("A" + action.amount);
    }
    return ret;
  };

  const autoScrollNav = () => {
    window.requestAnimationFrame(() => {
      const selectedChild =
        navRef.current?.children[selectedSpotIndexRef.current];
      selectedChild?.scrollIntoView({ behavior: "smooth", inline: "center" });
    });
  };

  const pushResultsTerminal = () => {
    const currentSpots = spotsRef.current;
    const prevSpot = currentSpots[
      selectedSpotIndexRef.current - 1
    ] as SpotPlayer;
    const prevAction = prevSpot.actions[prevSpot.selectedIndex];

    let equityOop = -1;
    if (prevAction.name === "Fold") {
      equityOop = prevSpot.player === "oop" ? 0 : 1;
    }

    setSpotsValue([
      ...currentSpots,
      {
        type: "terminal",
        index: selectedSpotIndexRef.current,
        player: "end",
        selectedIndex: -1,
        prevPlayer: prevSpot.player,
        equityOop,
        pot:
          config.startingPot +
          totalBetAmountRef.current[0] +
          totalBetAmountRef.current[1],
      },
    ]);
  };

  const pushResultsChance = async () => {
    type SpotTurn = SpotRoot | SpotChance;
    const currentSpots = spotsRef.current;
    const prevSpot = currentSpots[
      selectedSpotIndexRef.current - 1
    ] as SpotPlayer;
    const turnSpot = currentSpots.find((spot) => spot.player === "turn") as
      | SpotTurn
      | undefined;
    const nextActions = await invokes.treeActions();

    setSpotsValue([
      ...currentSpots,
      {
        type: "chance",
        index: selectedSpotIndexRef.current,
        player: turnSpot ? "river" : "turn",
        selectedIndex: -1,
        prevPlayer: prevSpot.player,
        cards: Array.from({ length: 52 }, (_, i) => ({
          card: i,
          isSelected: false,
          isDead: true,
        })),
        pot: config.startingPot + 2 * totalBetAmountRef.current[0],
        stack: config.effectiveStack - totalBetAmountRef.current[0],
      },
      {
        type: "player",
        index: selectedSpotIndexRef.current + 1,
        player: "oop",
        selectedIndex: -1,
        actions: nextActions.map((action, i) => {
          const [name, amount] = action.split(":");
          return { index: i, name, amount, isSelected: false, color: "#000" };
        }),
      },
    ]);
  };

  const pushResultsPlayer = async () => {
    const currentSpots = spotsRef.current;
    const prevSpot = currentSpots[selectedSpotIndexRef.current - 1];
    const player = prevSpot.player === "oop" ? "ip" : "oop";
    const actions = await invokes.treeActions();

    setSpotsValue([
      ...currentSpots,
      {
        type: "player",
        index: selectedSpotIndexRef.current,
        player,
        selectedIndex: -1,
        actions: actions.map((action, i) => {
          const [name, amount] = action.split(":");
          return { index: i, name, amount, isSelected: false, color: "#000" };
        }),
      },
    ]);
  };

  const selectSpot = async (
    spotIndex: number,
    needSplice: boolean,
    needRebuild: boolean,
    needAmountUpdate: boolean
  ) => {
    if (
      !needSplice &&
      !needRebuild &&
      spotIndex === selectedSpotIndexRef.current
    ) {
      return;
    }

    if (spotIndex === 0) {
      await selectSpot(1, true, false, selectedSpotIndexRef.current !== 1);
      return;
    }

    if (!needSplice && spotsRef.current[spotIndex]?.type === "chance") {
      await selectSpot(spotIndex + 1, false, false, true);
      return;
    }

    isLockedRef.current = true;

    if (needRebuild) {
      const selectedSpotIndexTmp = selectedSpotIndexRef.current;
      const line = encodeLine(spotsRef.current.length - 1);
      setSpotsValue([rootSpot]);
      setSelectedValue(1);
      setTotalValue([0, 0]);

      await invokes.treeBackToRoot();
      await pushResultsPlayer();

      for (let i = 0; i < line.length; ++i) {
        const index = await invokes.treePlay(line[i]);
        if (index === -1) {
          needAmountUpdate = true;
          break;
        }

        const nextSpots = [...spotsRef.current];
        const spot = {
          ...(nextSpots[selectedSpotIndexRef.current] as SpotPlayer),
        };
        const actions = spot.actions.map((action) => ({ ...action }));
        actions[index].isSelected = true;
        spot.selectedIndex = index;
        spot.actions = actions;
        nextSpots[selectedSpotIndexRef.current] = spot;
        setSpotsValue(nextSpots);

        setSelectedValue(selectedSpotIndexRef.current + 1);
        setTotalValue(await invokes.treeTotalBetAmount());

        if (await invokes.treeIsTerminalNode()) {
          pushResultsTerminal();
        } else if (await invokes.treeIsChanceNode()) {
          await pushResultsChance();
          setSelectedValue(selectedSpotIndexRef.current + 1);
        } else {
          await pushResultsPlayer();
        }
      }

      if (selectedSpotIndexTmp < selectedSpotIndexRef.current) {
        setSelectedValue(selectedSpotIndexTmp);
      }
    } else {
      setSelectedValue(spotIndex);
    }

    const line = encodeLine(selectedSpotIndexRef.current);
    await invokes.treeApplyHistory(line);
    setTotalValue(await invokes.treeTotalBetAmount());

    if (needSplice) {
      setSpotsValue(spotsRef.current.slice(0, selectedSpotIndexRef.current));
      if (await invokes.treeIsTerminalNode()) {
        pushResultsTerminal();
      } else if (await invokes.treeIsChanceNode()) {
        await pushResultsChance();
        setSelectedValue(selectedSpotIndexRef.current + 1);
      } else {
        await pushResultsPlayer();
      }
    }

    const prev = spotsRef.current[selectedSpotIndexRef.current - 1];
    if (prev?.type === "player") {
      setPrevBetAmount(Number(prev.actions[prev.selectedIndex].amount));
    } else {
      setPrevBetAmount(0);
    }

    if (needAmountUpdate) {
      setBetAmount(minAmount);
    }

    isLockedRef.current = false;
    autoScrollNav();
  };

  const play = async (spotIndex: number, actionIndex: number) => {
    const nextSpots = [...spotsRef.current];
    const spot = { ...(nextSpots[spotIndex] as SpotPlayer) };
    spot.actions = spot.actions.map((action, index) => ({
      ...action,
      isSelected: index === actionIndex,
    }));
    spot.selectedIndex = actionIndex;
    nextSpots[spotIndex] = spot;
    setSpotsValue(nextSpots);
    await selectSpot(spotIndex + 1, true, false, true);
  };

  const addBetAction = async () => {
    const isRaise =
      totalBetAmountRef.current[0] !== totalBetAmountRef.current[1];
    await invokes.treeAddBetAction(betAmount, isRaise);
    await selectSpot(selectedSpotIndexRef.current, false, true, false);
    await refreshLines();
  };

  const removeSelectedNode = async () => {
    await invokes.treeRemoveCurrentNode();
    let prevIndex = selectedSpotIndexRef.current - 1;
    if (spotsRef.current[prevIndex].type === "chance") prevIndex -= 1;
    await selectSpot(prevIndex, false, true, true);
    await refreshLines();
  };

  const deleteAddedLine = async (index: number) => {
    const line = addedLines.split(",")[index];
    await invokes.treeDeleteAddedLine(line);
    await selectSpot(selectedSpotIndexRef.current, false, true, false);
    await refreshLines();
  };

  const deleteRemovedLine = async (index: number) => {
    const line = removedLines.split(",")[index];
    await invokes.treeDeleteRemovedLine(line);
    await selectSpot(selectedSpotIndexRef.current, false, true, false);
    await refreshLines();
  };

  useEffect(() => {
    let cancelled = false;
    const init = async () => {
      setIsLoading(true);
      const ok = await invokes.treeNew(
        boardLength,
        config.startingPot,
        config.effectiveStack,
        config.donkOption,
        convertBetString(config.oopFlopBet),
        convertBetString(config.oopFlopRaise),
        convertBetString(config.oopTurnBet),
        convertBetString(config.oopTurnRaise),
        config.donkOption ? convertBetString(config.oopTurnDonk) : "",
        convertBetString(config.oopRiverBet),
        convertBetString(config.oopRiverRaise),
        config.donkOption ? convertBetString(config.oopRiverDonk) : "",
        convertBetString(config.ipFlopBet),
        convertBetString(config.ipFlopRaise),
        convertBetString(config.ipTurnBet),
        convertBetString(config.ipTurnRaise),
        convertBetString(config.ipRiverBet),
        convertBetString(config.ipRiverRaise),
        config.addAllInThreshold / 100,
        config.forceAllInThreshold / 100,
        config.mergingThreshold / 100,
        config.addedLines,
        config.removedLines
      );

      if (cancelled) return;
      if (!ok) {
        setIsTreeError(true);
        setIsLoading(false);
        return;
      }

      setIsTreeError(false);
      setSpotsValue([rootSpot]);
      setSelectedValue(-1);
      setTotalValue([0, 0]);
      await refreshLines();
      await selectSpot(0, true, false, true);
      if (!cancelled) setIsLoading(false);
    };

    init();
    return () => {
      cancelled = true;
    };
  }, []);

  if (isLoading) return <div>Loading...</div>;
  if (isTreeError)
    return <div>Error: Failed to build tree (loaded broken tree?)</div>;

  const disableAddBet =
    isSelectedTerminal ||
    isAfterAllin ||
    betAmount < minAmount ||
    betAmount > maxAmount ||
    betAmount % 1 !== 0 ||
    existingAmounts.includes(betAmount);

  return (
    <div>
      <div
        className="snug flex h-[10.5rem] gap-1 overflow-x-auto whitespace-nowrap p-1"
        ref={navRef}
      >
        {spots.map((spot) => (
          <div
            className={[
              "group flex h-full flex-col justify-start rounded-lg border-[3px] px-1 py-0.5 shadow-md transition",
              spot.type === "chance"
                ? "hover:border-red-600"
                : "hover:border-blue-600",
              spot.index === selectedSpotIndex
                ? "cursor-default border-blue-600"
                : "cursor-pointer border-gray-400",
            ].join(" ")}
            key={spot.index}
            onClick={() => selectSpot(spot.index, false, false, true)}
          >
            {(spot.type === "root" || spot.type === "chance") && (
              <>
                <div className="px-1.5 pb-0.5 pt-1 font-semibold opacity-70 group-hover:opacity-100">
                  {spot.player.toUpperCase()}
                </div>
                <div className="flex flex-grow flex-col items-center justify-evenly px-3 font-semibold">
                  <div className="opacity-70 group-hover:opacity-100">
                    <div>Pot {spot.pot}</div>
                    <div>Stack {spot.stack}</div>
                  </div>
                </div>
              </>
            )}

            {spot.type === "player" && (
              <>
                <div
                  className={[
                    "px-1.5 py-1 font-semibold group-hover:opacity-100",
                    spot.index === selectedSpotIndex ? "" : "opacity-70",
                  ].join(" ")}
                >
                  {spot.player.toUpperCase()}
                </div>
                <div className="flex-grow overflow-y-auto">
                  {spot.actions.map((action) => (
                    <button
                      className={[
                        "flex w-full rounded-md px-1.5 transition-colors hover:bg-blue-100",
                        action.isSelected ? "bg-blue-100" : "",
                      ].join(" ")}
                      key={action.index}
                      onClick={(event) => {
                        event.stopPropagation();
                        play(spot.index, action.index);
                      }}
                      type="button"
                    >
                      <span className="relative mr-0.5 inline-block w-4">
                        {action.isSelected && (
                          <CheckIcon className="absolute -left-0.5 top-[0.1875rem] h-4 w-4" />
                        )}
                      </span>
                      <span
                        className={[
                          "pr-0.5 font-semibold group-hover:opacity-100",
                          action.isSelected || spot.index === selectedSpotIndex
                            ? ""
                            : "opacity-70",
                        ].join(" ")}
                      >
                        {action.name}{" "}
                        {action.amount === "0" ? "" : action.amount}
                      </span>
                    </button>
                  ))}
                  {spot.actions.length === 0 && (
                    <div
                      className={[
                        "flex w-full px-1.5 font-semibold group-hover:opacity-100",
                        spot.index === selectedSpotIndex ? "" : "opacity-70",
                      ].join(" ")}
                    >
                      (No actions)
                    </div>
                  )}
                </div>
              </>
            )}

            {spot.type === "terminal" && (
              <>
                <div
                  className={[
                    "px-1.5 pb-0.5 pt-1 font-semibold group-hover:opacity-100",
                    spot.index === selectedSpotIndex ? "" : "opacity-70",
                  ].join(" ")}
                >
                  {spot.player.toUpperCase()}
                </div>
                <div
                  className={[
                    "flex flex-grow flex-col items-center justify-evenly font-semibold group-hover:opacity-100",
                    spot.index === selectedSpotIndex ? "" : "opacity-70",
                  ].join(" ")}
                >
                  {(spot.equityOop === 0 || spot.equityOop === 1) && (
                    <div className="px-3">
                      {["IP", "OOP"][spot.equityOop]} Wins
                    </div>
                  )}
                  <div className="px-3">Pot {spot.pot}</div>
                </div>
              </>
            )}
          </div>
        ))}
      </div>

      {invalidLinesArray.length > 0 && (
        <div className="mt-4 flex font-semibold text-red-500">
          <div className="underline">
            Invalid Terminal{invalidLinesArray.length > 1 ? "s" : ""}:
          </div>
          <div className="ml-2">
            {invalidLinesArray.map((line) => (
              <div key={line}>{line}</div>
            ))}
          </div>
        </div>
      )}

      <div className="mx-6 my-6 flex justify-center">
        <hr className="w-full border-gray-400" />
      </div>

      <div className="flex gap-3">
        <button
          className="button-base button-blue"
          disabled={disableAddBet}
          onClick={addBetAction}
          type="button"
        >
          Add Bet Action
        </button>
        <button
          className="button-base button-red"
          disabled={selectedSpotIndex === 1}
          onClick={removeSelectedNode}
          type="button"
        >
          Remove Selected Node
        </button>
        <div className="pl-3">
          Bet amount:
          <input
            className={[
              "ml-2 w-24 rounded-lg px-2 py-1 text-center text-sm",
              betAmount < minAmount ||
              betAmount > maxAmount ||
              betAmount % 1 !== 0
                ? "input-error"
                : "",
            ].join(" ")}
            max={maxAmount}
            min={minAmount}
            onChange={(event) => setBetAmount(Number(event.target.value))}
            onKeyDown={(event) => {
              if (event.key === "Enter" && !disableAddBet) addBetAction();
            }}
            type="number"
            value={betAmount}
          />
          {!isSelectedTerminal && !isAfterAllin && (
            <span className="ml-2">
              ({(amountRate * 100).toFixed(1)}% of the pot)
            </span>
          )}
        </div>
      </div>

      <div className="mx-6 my-6 flex justify-center">
        <hr className="w-full border-gray-400" />
      </div>

      <div className="my-6 flex gap-3">
        <button
          className="button-base button-blue"
          disabled={invalidLinesArray.length > 0}
          onClick={() => onSave(addedLines, removedLines)}
          type="button"
        >
          Save Edit
        </button>
        <button
          className="button-base button-red"
          onClick={onCancel}
          type="button"
        >
          Cancel Edit
        </button>
      </div>

      {(addedLinesArray.length > 0 || removedLinesArray.length > 0) && (
        <div>
          {addedLinesArray.length > 0 && (
            <div className="flex">
              <div className="w-[7.75rem] font-semibold underline">
                Added line{addedLinesArray.length > 1 ? "s" : ""}:
              </div>
              <div className="flex flex-col">
                {addedLinesArray.map((line, index) => (
                  <div className="flex items-center" key={line}>
                    <button
                      className="mr-2"
                      onClick={() => deleteAddedLine(index)}
                      type="button"
                    >
                      <TrashIcon className="h-5 w-5 text-gray-600" />
                    </button>
                    <span>{line}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {removedLinesArray.length > 0 && (
            <div className="mt-2 flex">
              <div className="w-[7.75rem] font-semibold underline">
                Removed line{removedLinesArray.length > 1 ? "s" : ""}:
              </div>
              <div className="flex flex-col">
                {removedLinesArray.map((line, index) => (
                  <div className="flex items-center" key={line}>
                    <button
                      className="mr-2"
                      onClick={() => deleteRemovedLine(index)}
                      type="button"
                    >
                      <TrashIcon className="h-5 w-5 text-gray-600" />
                    </button>
                    <span>{line}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// src/components/TreeEditor.vue
<template>
  <!-- Error -->

  <div v-if="isTreeError">
    Error: Failed to build tree (loaded broken tree?)
  </div>

  <!-- Navigation -->

  <div
    v-if="!isTreeError"
    ref="navDiv"
    class="flex h-[10.5rem] gap-1 p-1 overflow-x-auto whitespace-nowrap snug"
  >
    <div
      v-for="spot in spots"
      :key="spot.index"
      :class="
        'flex flex-col h-full px-1 py-0.5 justify-start ' +
        'rounded-lg shadow-md border-[3px] transition group ' +
        (spot.type === 'chance'
          ? 'hover:border-red-600 '
          : 'hover:border-blue-600 ') +
        (spot.index === selectedSpotIndex
          ? 'border-blue-600 cursor-default'
          : 'border-gray-400 cursor-pointer')
      "
      @click="selectSpot(spot.index, false, false, true)"
    >
      <!-- Root or Chance -->
      <template v-if="spot.type === 'root' || spot.type === 'chance'">
        <div
          class="px-1.5 pt-1 pb-0.5 font-semibold group-hover:opacity-100 opacity-70"
        >
          {{ spot.player.toUpperCase() }}
        </div>
        <div
          class="flex flex-col flex-grow px-3 items-center justify-evenly font-semibold"
        >
          <div class="group-hover:opacity-100 opacity-70">
            <div>Pot {{ spot.pot }}</div>
            <div>Stack {{ spot.stack }}</div>
          </div>
        </div>
      </template>

      <!-- Player -->
      <template v-if="spot.type === 'player'">
        <div
          :class="
            'px-1.5 py-1 font-semibold group-hover:opacity-100 ' +
            (spot.index === selectedSpotIndex ? '' : 'opacity-70')
          "
        >
          {{ spot.player.toUpperCase() }}
        </div>
        <div class="flex-grow overflow-y-auto">
          <button
            v-for="action of spot.actions"
            :key="action.index"
            :class="
              'flex w-full px-1.5 rounded-md transition-colors hover:bg-blue-100 ' +
              (action.isSelected ? 'bg-blue-100 ' : '')
            "
            @click.stop="play(spot.index, action.index)"
          >
            <span class="inline-block relative w-4 mr-0.5">
              <span v-if="action.isSelected">
                <CheckIcon class="absolute top-[0.1875rem] -left-0.5 w-4 h-4" />
              </span>
            </span>
            <span
              :class="
                'pr-0.5 font-semibold group-hover:opacity-100 ' +
                (action.isSelected || spot.index === selectedSpotIndex
                  ? ''
                  : 'opacity-70')
              "
            >
              {{ action.name }}
              {{ action.amount === "0" ? "" : action.amount }}
            </span>
          </button>
          <div
            v-if="spot.actions.length === 0"
            :class="
              'flex w-full px-1.5 font-semibold group-hover:opacity-100 ' +
              (spot.index === selectedSpotIndex ? '' : 'opacity-70')
            "
          >
            (No actions)
          </div>
        </div>
      </template>

      <!-- Terminal -->
      <template v-else-if="spot.type === 'terminal'">
        <div
          :class="
            'px-1.5 pt-1 pb-0.5 font-semibold group-hover:opacity-100 ' +
            (spot.index === selectedSpotIndex ? '' : 'opacity-70')
          "
        >
          {{ spot.player.toUpperCase() }}
        </div>
        <div
          :class="
            'flex flex-col flex-grow items-center justify-evenly font-semibold group-hover:opacity-100 ' +
            (spot.index === selectedSpotIndex ? '' : 'opacity-70')
          "
        >
          <div v-if="spot.equityOop === 0 || spot.equityOop === 1" class="px-3">
            {{ ["IP", "OOP"][spot.equityOop] }} Wins
          </div>
          <div class="px-3">Pot {{ spot.pot }}</div>
        </div>
      </template>
    </div>
  </div>

  <!-- Invalid lines error -->

  <div
    v-if="!isTreeError && invalidLinesArray.length > 0"
    class="flex mt-4 font-semibold text-red-500"
  >
    <div class="underline">
      Invalid Terminal{{ invalidLinesArray.length > 1 ? "s" : "" }}:
    </div>
    <div class="ml-2">
      <div v-for="invalidLine in invalidLinesArray" :key="invalidLine">
        {{ invalidLine }}
      </div>
    </div>
  </div>

  <div v-if="!isTreeError" class="flex mx-6 my-6 justify-center">
    <hr class="border-gray-400 w-full" />
  </div>

  <!-- Edit -->

  <div v-if="!isTreeError" class="flex gap-3">
    <button
      :disabled="
        isSelectedTerminal ||
        isAfterAllin ||
        betAmount < minAmount ||
        betAmount > maxAmount ||
        betAmount % 1 !== 0 ||
        existingAmounts.includes(betAmount)
      "
      class="button-base button-blue"
      @click="addBetAction"
    >
      Add Bet Action
    </button>

    <button
      :disabled="selectedSpotIndex === 1"
      class="button-base button-red"
      @click="removeSelectedNode"
    >
      Remove Selected Node
    </button>

    <div class="pl-3">
      Bet amount:
      <input
        v-model="betAmount"
        :class="
          'w-24 ml-2 px-2 py-1 rounded-lg text-sm text-center ' +
          (betAmount < minAmount || betAmount > maxAmount || betAmount % 1 !== 0
            ? 'input-error'
            : '')
        "
        :max="maxAmount"
        :min="minAmount"
        type="number"
        @keydown.enter="addBetAction"
      />
      <span v-if="!isSelectedTerminal && !isAfterAllin" class="ml-2">
        ({{ (amountRate * 100).toFixed(1) }}% of the pot)
      </span>
    </div>
  </div>

  <div class="flex mx-6 my-6 justify-center">
    <hr class="border-gray-400 w-full" />
  </div>

  <!-- Save/Cancel -->

  <div class="flex my-6 gap-3">
    <button
      :disabled="isTreeError || invalidLinesArray.length > 0"
      class="button-base button-blue"
      @click="saveEdit"
    >
      Save Edit
    </button>

    <button class="button-base button-red" @click="cancelEdit">
      Cancel Edit
    </button>
  </div>

  <!-- Lines -->

  <div
    v-if="
      !isTreeError &&
      (addedLinesArray.length > 0 || removedLinesArray.length > 0)
    "
  >
    <div v-if="addedLinesArray.length > 0" class="flex">
      <div class="font-semibold underline w-[7.75rem]">
        Added line{{ addedLinesArray.length > 1 ? "s" : "" }}:
      </div>
      <div class="flex flex-col">
        <div
          v-for="(addedLine, index) in addedLinesArray"
          :key="addedLine"
          class="flex items-center"
        >
          <button class="mr-2" @click="deleteAddedLine(index)">
            <TrashIcon class="w-5 h-5 text-gray-600" />
          </button>
          <span>{{ addedLine }}</span>
        </div>
      </div>
    </div>

    <div v-if="removedLinesArray.length > 0" class="flex mt-2">
      <div class="font-semibold underline w-[7.75rem]">
        Removed line{{ removedLinesArray.length > 1 ? "s" : "" }}:
      </div>
      <div class="flex flex-col">
        <div
          v-for="(removedLine, index) in removedLinesArray"
          :key="removedLine"
          class="flex items-center"
        >
          <button class="mr-2" @click="deleteRemovedLine(index)">
            <TrashIcon class="w-5 h-5 text-gray-600" />
          </button>
          <span>{{ removedLine }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed, nextTick, ref } from "vue";
import { useConfigStore } from "../store";
import { convertBetString, readableLineString } from "../utils";
import { Spot, SpotChance, SpotPlayer, SpotRoot } from "../result-types";
import * as invokes from "../invokes";

import { CheckIcon } from "@heroicons/vue/20/solid";
import { TrashIcon } from "@heroicons/vue/24/outline";

const emit = defineEmits<{
  (event: "save", addedLines: string, removedLines: string): void;
  (event: "cancel"): void;
}>();

const navDiv = ref(null as HTMLDivElement | null);

const config = useConfigStore();
let isLocked = false;

const boardLength = config.expectedBoardLength;

const isTreeError = !(await invokes.treeNew(
  boardLength,
  config.startingPot,
  config.effectiveStack,
  config.donkOption,
  convertBetString(config.oopFlopBet),
  convertBetString(config.oopFlopRaise),
  convertBetString(config.oopTurnBet),
  convertBetString(config.oopTurnRaise),
  config.donkOption ? convertBetString(config.oopTurnDonk) : "",
  convertBetString(config.oopRiverBet),
  convertBetString(config.oopRiverRaise),
  config.donkOption ? convertBetString(config.oopRiverDonk) : "",
  convertBetString(config.ipFlopBet),
  convertBetString(config.ipFlopRaise),
  convertBetString(config.ipTurnBet),
  convertBetString(config.ipTurnRaise),
  convertBetString(config.ipRiverBet),
  convertBetString(config.ipRiverRaise),
  config.addAllInThreshold / 100,
  config.forceAllInThreshold / 100,
  config.mergingThreshold / 100,
  config.addedLines,
  config.removedLines
));

const rootSpot: SpotRoot = {
  type: "root",
  index: 0,
  player: boardLength === 3 ? "flop" : boardLength === 4 ? "turn" : "river",
  selectedIndex: -1,
  board: config.board,
  pot: config.startingPot,
  stack: config.effectiveStack,
};
const spots = ref<Spot[]>([rootSpot]);
const selectedSpotIndex = ref(-1);

const isSelectedTerminal = computed(() => {
  if (isLocked || selectedSpotIndex.value === -1) return false;
  const selectedSpot = spots.value[selectedSpotIndex.value];
  return selectedSpot.type === "terminal";
});

const betAmount = ref(0);
const totalBetAmount = ref([0, 0]);
const prevBetAmount = ref(0);

const isAfterAllin = computed(() => {
  const maxTotalBetAmount = Math.max(...totalBetAmount.value);
  return maxTotalBetAmount === config.effectiveStack;
});

const maxAmount = computed(() => {
  if (isSelectedTerminal.value) return 0;
  const maxTotalBetAmount = Math.max(...totalBetAmount.value);
  return config.effectiveStack - (maxTotalBetAmount - prevBetAmount.value);
});

const minAmount = computed(() => {
  const betMinus = config.effectiveStack - maxAmount.value;
  const min = Math.min(...totalBetAmount.value) - betMinus;
  const max = Math.max(...totalBetAmount.value) - betMinus;
  return Math.min(Math.max(2 * max - min, 1), maxAmount.value);
});

const amountRate = computed(() => {
  const pot = config.startingPot + 2 * Math.max(...totalBetAmount.value);
  const amount = betAmount.value - prevBetAmount.value;
  return amount / pot;
});

const existingAmounts = computed(() => {
  if (isLocked || selectedSpotIndex.value === -1) return [];
  const ret: number[] = [];
  const spot = spots.value[selectedSpotIndex.value] as SpotPlayer;
  for (const action of spot.actions) {
    if (action.amount !== "0") {
      ret.push(Number(action.amount));
    }
  }
  return ret;
});

const addedLines = ref(await invokes.treeAddedLines());
const removedLines = ref(await invokes.treeRemovedLines());
const invalidLines = ref(await invokes.treeInvalidTerminals());

const addedLinesArray = computed(() =>
  addedLines.value === ""
    ? []
    : addedLines.value.split(",").map(readableLineString)
);

const removedLinesArray = computed(() =>
  removedLines.value === ""
    ? []
    : removedLines.value.split(",").map(readableLineString)
);

const invalidLinesArray = computed(() =>
  invalidLines.value === ""
    ? []
    : invalidLines.value.split(",").map(readableLineString)
);

const encodeLine = (spotIndex: number) => {
  const ret: string[] = [];
  for (let i = 1; i < spotIndex; ++i) {
    const spot = spots.value[i];
    if (spot.type === "player") {
      const action = spot.actions[spot.selectedIndex];
      if (action.name === "Fold") {
        ret.push("F");
      } else if (action.name === "Check") {
        ret.push("X");
      } else if (action.name === "Call") {
        ret.push("C");
      } else if (action.name === "Bet") {
        ret.push("B" + action.amount);
      } else if (action.name === "Raise") {
        ret.push("R" + action.amount);
      } else if (action.name === "Allin") {
        ret.push("A" + action.amount);
      }
    }
  }
  return ret;
};

const selectSpot = async (
  spotIndex: number,
  needSplice: boolean,
  needRebuild: boolean,
  needAmountUpdate: boolean
) => {
  if (!needSplice && !needRebuild && spotIndex === selectedSpotIndex.value) {
    return;
  }

  if (spotIndex === 0) {
    await selectSpot(1, true, false, selectedSpotIndex.value !== 1);
    return;
  }

  if (!needSplice && spots.value[spotIndex]?.type === "chance") {
    await selectSpot(spotIndex + 1, false, false, true);
    return;
  }

  isLocked = true;

  if (needRebuild) {
    const selectedSpotIndexTmp = selectedSpotIndex.value;
    const line = encodeLine(spots.value.length - 1);
    spots.value = [rootSpot];

    selectedSpotIndex.value = 1;
    totalBetAmount.value = [0, 0];

    await invokes.treeBackToRoot();
    await pushResultsPlayer();

    for (let i = 0; i < line.length; ++i) {
      const index = await invokes.treePlay(line[i]);
      if (index === -1) {
        needAmountUpdate = true;
        break;
      }

      const spot = spots.value[selectedSpotIndex.value] as SpotPlayer;
      const action = spot.actions[index];
      spot.selectedIndex = index;
      action.isSelected = true;

      ++selectedSpotIndex.value;
      totalBetAmount.value = await invokes.treeTotalBetAmount();

      if (await invokes.treeIsTerminalNode()) {
        pushResultsTerminal();
      } else if (await invokes.treeIsChanceNode()) {
        await pushResultsChance();
        ++selectedSpotIndex.value;
      } else {
        await pushResultsPlayer();
      }
    }

    if (selectedSpotIndexTmp < selectedSpotIndex.value) {
      selectedSpotIndex.value = selectedSpotIndexTmp;
    }
  } else {
    selectedSpotIndex.value = spotIndex;
  }

  const line = encodeLine(selectedSpotIndex.value);
  await invokes.treeApplyHistory(line);
  totalBetAmount.value = await invokes.treeTotalBetAmount();

  if (needSplice) {
    spots.value.splice(selectedSpotIndex.value);
    if (await invokes.treeIsTerminalNode()) {
      pushResultsTerminal();
    } else if (await invokes.treeIsChanceNode()) {
      await pushResultsChance();
      ++selectedSpotIndex.value;
    } else {
      await pushResultsPlayer();
    }
  }

  const prev = spots.value[selectedSpotIndex.value - 1];
  if (prev.type === "player") {
    prevBetAmount.value = Number(prev.actions[prev.selectedIndex].amount);
  } else {
    prevBetAmount.value = 0;
  }

  if (needAmountUpdate) {
    betAmount.value = minAmount.value;
  }

  isLocked = false;
  autoScrollNav();
};

const autoScrollNav = async () => {
  await nextTick();
  if (navDiv.value) {
    const selectedChild = navDiv.value.children[selectedSpotIndex.value];
    if (selectedChild) {
      selectedChild.scrollIntoView({
        behavior: "smooth",
        inline: "center",
      });
    }
  }
};

const pushResultsTerminal = () => {
  const prevSpot = spots.value[selectedSpotIndex.value - 1] as SpotPlayer;
  const prevAction = prevSpot.actions[prevSpot.selectedIndex];

  let equityOop = -1;
  if (prevAction.name === "Fold") {
    equityOop = prevSpot.player === "oop" ? 0 : 1;
  }

  spots.value.push({
    type: "terminal",
    index: selectedSpotIndex.value,
    player: "end",
    selectedIndex: -1,
    prevPlayer: prevSpot.player,
    equityOop,
    pot: config.startingPot + totalBetAmount.value[0] + totalBetAmount.value[1],
  });
};

const pushResultsChance = async () => {
  type SpotTurn = SpotRoot | SpotChance;
  const prevSpot = spots.value[selectedSpotIndex.value - 1] as SpotPlayer;
  const turnSpot = spots.value.find((spot) => spot.player === "turn") as
    | SpotTurn
    | undefined;

  const nextActions = await invokes.treeActions();

  spots.value.push(
    {
      type: "chance",
      index: selectedSpotIndex.value,
      player: turnSpot ? "river" : "turn",
      selectedIndex: -1,
      prevPlayer: prevSpot.player,
      cards: Array.from({ length: 52 }, (_, i) => ({
        card: i,
        isSelected: false,
        isDead: true,
      })),
      pot: config.startingPot + 2 * totalBetAmount.value[0],
      stack: config.effectiveStack - totalBetAmount.value[0],
    },
    {
      type: "player",
      index: selectedSpotIndex.value + 1,
      player: "oop",
      selectedIndex: -1,
      actions: nextActions.map((action, i) => {
        const [name, amount] = action.split(":");
        return {
          index: i,
          name,
          amount,
          rate: -1,
          isSelected: false,
          color: "#000",
        };
      }),
    }
  );
};

const pushResultsPlayer = async () => {
  const prevSpot = spots.value[selectedSpotIndex.value - 1];
  const player = prevSpot.player === "oop" ? "ip" : "oop";

  const actions = await invokes.treeActions();

  spots.value.push({
    type: "player",
    index: selectedSpotIndex.value,
    player,
    selectedIndex: -1,
    actions: actions.map((action, i) => {
      const [name, amount] = action.split(":");
      return {
        index: i,
        name,
        amount,
        isSelected: false,
        color: "#000",
      };
    }),
  });
};

const play = async (spotIndex: number, actionIndex: number) => {
  const spot = spots.value[spotIndex] as SpotPlayer;

  if (spot.selectedIndex !== -1) {
    spot.actions[spot.selectedIndex].isSelected = false;
  }
  spot.actions[actionIndex].isSelected = true;
  spot.selectedIndex = actionIndex;

  await selectSpot(spotIndex + 1, true, false, true);
};

const addBetAction = async () => {
  const isRaise = totalBetAmount.value[0] !== totalBetAmount.value[1];
  await invokes.treeAddBetAction(betAmount.value, isRaise);
  await selectSpot(selectedSpotIndex.value, false, true, false);
  addedLines.value = await invokes.treeAddedLines();
  removedLines.value = await invokes.treeRemovedLines();
  invalidLines.value = await invokes.treeInvalidTerminals();
};

const removeSelectedNode = async () => {
  await invokes.treeRemoveCurrentNode();
  let prevIndex = selectedSpotIndex.value - 1;
  if (spots.value[prevIndex].type === "chance") --prevIndex;
  await selectSpot(prevIndex, false, true, true);
  addedLines.value = await invokes.treeAddedLines();
  removedLines.value = await invokes.treeRemovedLines();
  invalidLines.value = await invokes.treeInvalidTerminals();
};

const saveEdit = () => {
  emit("save", addedLines.value, removedLines.value);
};

const cancelEdit = () => {
  emit("cancel");
};

const deleteAddedLine = async (index: number) => {
  const addedLinesArray = addedLines.value.split(",");
  const line = addedLinesArray[index];

  await invokes.treeDeleteAddedLine(line);
  await selectSpot(selectedSpotIndex.value, false, true, false);

  addedLines.value = await invokes.treeAddedLines();
  removedLines.value = await invokes.treeRemovedLines();
  invalidLines.value = await invokes.treeInvalidTerminals();
};

const deleteRemovedLine = async (index: number) => {
  const removedLinesArray = removedLines.value.split(",");
  const line = removedLinesArray[index];

  await invokes.treeDeleteRemovedLine(line);
  await selectSpot(selectedSpotIndex.value, false, true, false);

  addedLines.value = await invokes.treeAddedLines();
  removedLines.value = await invokes.treeRemovedLines();
  invalidLines.value = await invokes.treeInvalidTerminals();
};

await selectSpot(0, true, false, true);
</script>
