// src/components/RangeEditor.vue
<template>
  <div class="flex mt-1">
    <div class="shrink-0 ml-1">
      <table class="shadow-md select-none snug" @mouseleave="dragEnd">
        <tr v-for="row in 13" :key="row" class="h-9">
          <td
            v-for="col in 13"
            :key="col"
            class="relative w-[2.625rem] border border-black"
            @mousedown="dragStart(row, col)"
            @mouseenter="mouseEnter(row, col)"
            @mouseup="dragEnd"
          >
            <div
              :class="
                'absolute w-full h-full left-0 top-0 ' +
                (row === col ? 'bg-neutral-700' : 'bg-neutral-800')
              "
            >
              <div
                :style="{
                  'background-image': `linear-gradient(${yellow500} 0% 100%)`,
                  'background-size': `100% ${cellValue(row, col)}%`,
                }"
                class="absolute w-full h-full left-0 top-0 bg-bottom bg-no-repeat"
              ></div>
            </div>
            <div
              :class="
                'absolute -top-px left-[0.1875rem] z-10 text-shadow ' +
                (cellValue(row, col) > 0 ? 'text-white' : 'text-neutral-500')
              "
            >
              {{ cellText(row, col) }}
            </div>
            <div
              class="absolute bottom-px right-1 z-10 text-sm text-shadow text-white"
            >
              {{
                cellValue(row, col) > 0 && cellValue(row, col) < 100
                  ? cellValue(row, col).toFixed(1)
                  : ""
              }}
            </div>
          </td>
        </tr>
      </table>

      <div class="mt-5">
        <div class="flex">
          <input
            v-model="rangeText"
            :class="
              'flex-grow mr-6 px-2 py-1 rounded-lg text-sm ' +
              (rangeTextError ? 'input-error' : '')
            "
            type="text"
            @change="onRangeTextChange"
            @focus="($event.target as HTMLInputElement).select()"
          />

          <button
            v-if="player >= 2"
            class="mr-4 button-base button-blue"
            @click="invertRange"
          >
            Invert
          </button>

          <button class="button-base button-blue" @click="clearRange">
            Clear
          </button>
        </div>

        <div v-if="rangeTextError" class="mt-1 text-red-500">
          Error: {{ rangeTextError }}
        </div>
      </div>

      <div class="flex mt-3.5 items-center">
        <div>
          Weight:
          <input
            v-model="weight"
            class="ml-3 w-40 align-middle"
            max="100"
            min="0"
            step="5"
            type="range"
            @change="onWeightChange"
          />
          <input
            v-model="weight"
            :class="
              'w-20 ml-4 px-2 py-1 rounded-lg text-sm text-center ' +
              (weight < 0 || weight > 100 ? 'input-error' : '')
            "
            max="100"
            min="0"
            step="5"
            type="number"
            @change="onWeightChange"
          />
          %
        </div>

        <span class="inline-block ml-auto">
          {{ numCombos.toFixed(1) }} combos ({{
            ((numCombos * 100) / ((52 * 51) / 2)).toFixed(1)
          }}%)
        </span>
      </div>
    </div>

    <div class="flex-grow max-w-[18rem] ml-6">
      <DbItemPicker
        :allow-save="rangeText !== '' && rangeTextError === ''"
        :hide-import-export="player >= 2"
        :index="player"
        :value="rangeText"
        store-name="ranges"
        @load-item="loadRange"
      />

      <div v-if="player >= 2" class="flex mt-12 justify-center gap-4">
        <button class="button-base button-blue !px-5" @click="emit('save')">
          Save Edit
        </button>
        <button class="button-base button-red !px-5" @click="emit('cancel')">
          Cancel Edit
        </button>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { useStore } from "../store";
import { rangeRegex, ranks, trimRegex } from "../utils";
import * as invokes from "../invokes";

import DbItemPicker from "./DbItemPicker.vue";

const yellow500 = "#eab308";

type DraggingMode = "none" | "enabling" | "disabling";

const props = withDefaults(
  defineProps<{ player: number; defaultText?: string }>(),
  { defaultText: "" }
);

const emit = defineEmits<{
  (event: "save"): void;
  (event: "cancel"): void;
}>();

const store = useStore();
const rangeText = ref(props.defaultText);
const rangeTextError = ref("");
const weight = ref(100);
const numCombos = ref(0);

let draggingMode: DraggingMode = "none";

const cellText = (row: number, col: number) => {
  const r1 = 13 - Math.min(row, col);
  const r2 = 13 - Math.max(row, col);
  return ranks[r1] + ranks[r2] + ["s", "", "o"][Math.sign(row - col) + 1];
};

const cellIndex = (row: number, col: number) => {
  return 13 * (row - 1) + col - 1;
};

const cellValue = (row: number, col: number) => {
  return store.ranges[props.player][cellIndex(row, col)];
};

const onUpdate = async () => {
  rangeText.value = await invokes.rangeToString(props.player);
  numCombos.value = await invokes.rangeNumCombos(props.player);
  rangeTextError.value = "";
};

const update = async (row: number, col: number, weight: number) => {
  const idx = 13 * (row - 1) + col - 1;
  await invokes.rangeUpdate(props.player, row, col, weight / 100);
  store.ranges[props.player][idx] = weight;
  await onUpdate();
};

const onRangeTextChange = async () => {
  const trimmed = rangeText.value.replace(trimRegex, "$1").trim();
  const ranges = trimmed.split(",");

  if (ranges[ranges.length - 1] === "") {
    ranges.pop();
  }

  for (const range of ranges) {
    if (!rangeRegex.test(range)) {
      rangeTextError.value = `Failed to parse range: ${
        range || "(empty string)"
      }`;
      return;
    }
  }

  const errorString = await invokes.rangeFromString(props.player, trimmed);

  if (errorString) {
    rangeTextError.value = errorString;
  } else {
    const weights = await invokes.rangeGetWeights(props.player);
    for (let i = 0; i < 13 * 13; ++i) {
      store.ranges[props.player][i] = weights[i] * 100;
    }
    await onUpdate();
  }
};

const dragStart = (row: number, col: number) => {
  const idx = 13 * (row - 1) + col - 1;

  if (store.ranges[props.player][idx] !== weight.value) {
    draggingMode = "enabling";
    update(row, col, weight.value);
  } else {
    draggingMode = "disabling";
    update(row, col, 0);
  }
};

const dragEnd = () => {
  draggingMode = "none";
};

const mouseEnter = (row: number, col: number) => {
  if (draggingMode === "enabling") {
    update(row, col, weight.value);
  } else if (draggingMode === "disabling") {
    update(row, col, 0);
  }
};

const onWeightChange = () => {
  weight.value = Math.round(Math.max(0, Math.min(100, weight.value)));
};

const clearRange = async () => {
  await invokes.rangeClear(props.player);
  store.ranges[props.player].fill(0);
  rangeText.value = "";
  rangeTextError.value = "";
  weight.value = 100;
  numCombos.value = 0;
};

const invertRange = async () => {
  await invokes.rangeInvert(props.player);
  for (let i = 0; i < 13 * 13; ++i) {
    store.ranges[props.player][i] = 100 - store.ranges[props.player][i];
  }
  await onUpdate();
};

const loadRange = (rangeStr: unknown) => {
  rangeText.value = String(rangeStr);
  onRangeTextChange();
};
</script>

// src/features/ranges/RangeEditor.tsx
import { useRef, useState } from "react";
import { useAppDispatch, useAppSelector } from "../../app/hooks";
import { setRangeCell, setRangeWeights } from "../../app/slices/rangesSlice";
import { DbItemPicker } from "../database/DbItemPicker";
import * as invokes from "../../invokes";
import { rangeRegex, ranks, trimRegex } from "../../utils";

const yellow500 = "#eab308";
type DraggingMode = "none" | "enabling" | "disabling";

type RangeEditorProps = {
  player: number;
  defaultText?: string;
  onSave?: () => void;
  onCancel?: () => void;
};

function cellText(row: number, col: number) {
  const r1 = 13 - Math.min(row, col);
  const r2 = 13 - Math.max(row, col);
  return ranks[r1] + ranks[r2] + ["s", "", "o"][Math.sign(row - col) + 1];
}

function cellIndex(row: number, col: number) {
  return 13 * (row - 1) + col - 1;
}

export function RangeEditor({
  player,
  defaultText = "",
  onSave,
  onCancel,
}: RangeEditorProps) {
  const dispatch = useAppDispatch();
  const range = useAppSelector((state) => state.ranges.values[player]);
  const draggingMode = useRef<DraggingMode>("none");
  const [rangeText, setRangeText] = useState(defaultText);
  const [rangeTextError, setRangeTextError] = useState("");
  const [weight, setWeight] = useState(100);
  const [numCombos, setNumCombos] = useState(0);

  const cellValue = (row: number, col: number) =>
    range[cellIndex(row, col)] ?? 0;

  const refreshRangeText = async () => {
    setRangeText(await invokes.rangeToString(player));
    setNumCombos(await invokes.rangeNumCombos(player));
    setRangeTextError("");
  };

  const updateCell = async (row: number, col: number, nextWeight: number) => {
    const index = cellIndex(row, col);
    await invokes.rangeUpdate(player, row, col, nextWeight / 100);
    dispatch(setRangeCell({ player, index, weight: nextWeight }));
    await refreshRangeText();
  };

  const onRangeTextChange = async (text = rangeText) => {
    const trimmed = text.replace(trimRegex, "$1").trim();
    const ranges = trimmed.split(",");

    if (ranges[ranges.length - 1] === "") {
      ranges.pop();
    }

    for (const rangePart of ranges) {
      if (!rangeRegex.test(rangePart)) {
        setRangeTextError(
          `Failed to parse range: ${rangePart || "(empty string)"}`
        );
        return;
      }
    }

    const errorString = await invokes.rangeFromString(player, trimmed);

    if (errorString) {
      setRangeTextError(errorString);
      return;
    }

    const weights = await invokes.rangeGetWeights(player);
    dispatch(
      setRangeWeights({
        player,
        weights: weights.map((value) => value * 100),
      })
    );
    await refreshRangeText();
  };

  const dragStart = (row: number, col: number) => {
    const value = cellValue(row, col);
    if (value !== weight) {
      draggingMode.current = "enabling";
      updateCell(row, col, weight);
    } else {
      draggingMode.current = "disabling";
      updateCell(row, col, 0);
    }
  };

  const dragEnd = () => {
    draggingMode.current = "none";
  };

  const mouseEnter = (row: number, col: number) => {
    if (draggingMode.current === "enabling") {
      updateCell(row, col, weight);
    } else if (draggingMode.current === "disabling") {
      updateCell(row, col, 0);
    }
  };

  const onWeightChange = (value: number) => {
    setWeight(Math.round(Math.max(0, Math.min(100, value))));
  };

  const clearRange = async () => {
    await invokes.rangeClear(player);
    dispatch(
      setRangeWeights({
        player,
        weights: Array.from({ length: 13 * 13 }, () => 0),
      })
    );
    setRangeText("");
    setRangeTextError("");
    setWeight(100);
    setNumCombos(0);
  };

  const invertRange = async () => {
    await invokes.rangeInvert(player);
    dispatch(
      setRangeWeights({
        player,
        weights: range.map((value) => 100 - value),
      })
    );
    await refreshRangeText();
  };

  const loadRange = (rangeStr: unknown) => {
    const nextText = String(rangeStr);
    setRangeText(nextText);
    onRangeTextChange(nextText);
  };

  return (
    <div className="mt-1 flex">
      <div className="ml-1 shrink-0">
        <table className="snug select-none shadow-md" onMouseLeave={dragEnd}>
          <tbody>
            {Array.from({ length: 13 }, (_, rowIndex) => {
              const row = rowIndex + 1;
              return (
                <tr className="h-9" key={row}>
                  {Array.from({ length: 13 }, (_, colIndex) => {
                    const col = colIndex + 1;
                    const value = cellValue(row, col);
                    return (
                      <td
                        className="relative w-[2.625rem] border border-black"
                        key={col}
                        onMouseDown={() => dragStart(row, col)}
                        onMouseEnter={() => mouseEnter(row, col)}
                        onMouseUp={dragEnd}
                      >
                        <div
                          className={[
                            "absolute left-0 top-0 h-full w-full",
                            row === col ? "bg-neutral-700" : "bg-neutral-800",
                          ].join(" ")}
                        >
                          <div
                            className="absolute left-0 top-0 h-full w-full bg-bottom bg-no-repeat"
                            style={{
                              backgroundImage: `linear-gradient(${yellow500} 0% 100%)`,
                              backgroundSize: `100% ${value}%`,
                            }}
                          />
                        </div>
                        <div
                          className={[
                            "text-shadow absolute -top-px left-[0.1875rem] z-10",
                            value > 0 ? "text-white" : "text-neutral-500",
                          ].join(" ")}
                        >
                          {cellText(row, col)}
                        </div>
                        <div className="text-shadow absolute bottom-px right-1 z-10 text-sm text-white">
                          {value > 0 && value < 100 ? value.toFixed(1) : ""}
                        </div>
                      </td>
                    );
                  })}
                </tr>
              );
            })}
          </tbody>
        </table>

        <div className="mt-5">
          <div className="flex">
            <input
              className={[
                "mr-6 flex-grow rounded-lg px-2 py-1 text-sm",
                rangeTextError ? "input-error" : "",
              ].join(" ")}
              onChange={(event) => setRangeText(event.target.value)}
              onFocus={(event) => event.currentTarget.select()}
              onBlur={() => onRangeTextChange()}
              type="text"
              value={rangeText}
            />

            {player >= 2 && (
              <button
                className="button-base button-blue mr-4"
                onClick={invertRange}
                type="button"
              >
                Invert
              </button>
            )}

            <button
              className="button-base button-blue"
              onClick={clearRange}
              type="button"
            >
              Clear
            </button>
          </div>

          {rangeTextError && (
            <div className="mt-1 text-red-500">Error: {rangeTextError}</div>
          )}
        </div>

        <div className="mt-3.5 flex items-center">
          <div>
            Weight:
            <input
              className="ml-3 w-40 align-middle"
              max="100"
              min="0"
              onChange={(event) => onWeightChange(Number(event.target.value))}
              step="5"
              type="range"
              value={weight}
            />
            <input
              className={[
                "ml-4 w-20 rounded-lg px-2 py-1 text-center text-sm",
                weight < 0 || weight > 100 ? "input-error" : "",
              ].join(" ")}
              max="100"
              min="0"
              onChange={(event) => onWeightChange(Number(event.target.value))}
              step="5"
              type="number"
              value={weight}
            />
            %
          </div>

          <span className="ml-auto inline-block">
            {numCombos.toFixed(1)} combos (
            {((numCombos * 100) / ((52 * 51) / 2)).toFixed(1)}%)
          </span>
        </div>
      </div>

      <div className="ml-6 max-w-[18rem] flex-grow">
        <DbItemPicker
          allowSave={rangeText !== "" && rangeTextError === ""}
          hideImportExport={player >= 2}
          index={player}
          onLoadItem={loadRange}
          storeName="ranges"
          value={rangeText}
        />

        {player >= 2 && (
          <div className="mt-12 flex justify-center gap-4">
            <button
              className="button-base button-blue !px-5"
              onClick={onSave}
              type="button"
            >
              Save Edit
            </button>
            <button
              className="button-base button-red !px-5"
              onClick={onCancel}
              type="button"
            >
              Cancel Edit
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
