// src/components/RangeMiniViewer.vue
<template>
  <table class="shadow-md">
    <tr v-for="row in 13" :key="row" class="h-2.5">
      <td
        v-for="col in 13"
        :key="col"
        class="relative w-2.5 border-[0.5px] border-black"
      >
        <div
          :class="
            'absolute w-full h-full left-0 top-0 ' +
            (row === col ? 'bg-neutral-700' : 'bg-neutral-800')
          "
        >
          <div
            :style="{
              'background-image': `linear-gradient(${yellow500} 0% 100%)`,
              'background-size': `100% ${cellValue(row, col)}%`,
            }"
            class="absolute w-full h-full left-0 top-0 bg-bottom bg-no-repeat"
          ></div>
        </div>
      </td>
    </tr>
  </table>
</template>

<script lang="ts" setup>
import { useStore } from "../store";

const yellow500 = "#eab308";

const props = defineProps<{ player: number }>();
const store = useStore();

const cellValue = (row: number, col: number) => {
  const cellIndex = (row - 1) * 13 + (col - 1);
  return store.ranges[props.player][cellIndex];
};
</script>

// src/features/ranges/RangeMiniViewer.tsx
import { useAppSelector } from "../../app/hooks";

const yellow500 = "#eab308";

type RangeMiniViewerProps = {
  player: number;
};

export function RangeMiniViewer({ player }: RangeMiniViewerProps) {
  const range = useAppSelector((state) => state.ranges.values[player]);

  const cellValue = (row: number, col: number) => {
    const cellIndex = (row - 1) * 13 + (col - 1);
    return range[cellIndex] ?? 0;
  };

  return (
    <table className="shadow-md">
      <tbody>
        {Array.from({ length: 13 }, (_, rowIndex) => {
          const row = rowIndex + 1;
          return (
            <tr className="h-2.5" key={row}>
              {Array.from({ length: 13 }, (_, colIndex) => {
                const col = colIndex + 1;
                return (
                  <td
                    className="relative w-2.5 border-[0.5px] border-black"
                    key={col}
                  >
                    <div
                      className={[
                        "absolute left-0 top-0 h-full w-full",
                        row === col ? "bg-neutral-700" : "bg-neutral-800",
                      ].join(" ")}
                    >
                      <div
                        className="absolute left-0 top-0 h-full w-full bg-bottom bg-no-repeat"
                        style={{
                          backgroundImage: `linear-gradient(${yellow500} 0% 100%)`,
                          backgroundSize: `100% ${cellValue(row, col)}%`,
                        }}
                      />
                    </div>
                  </td>
                );
              })}
            </tr>
          );
        })}
      </tbody>
    </table>
  );
}
